# version: "3.9"
services:
    laravel:
        container_name: ba_laravel
        image: "agusedyc/aec-php:8.3-fpm-nginx"
        restart: unless-stopped
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - .:/app:delegated
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 24051:80
        links:
            - mariadb
        environment:
            - TZ=Asia/Jakarta
    mariadb:
        container_name: ba_mariadb
        image: mariadb:10.3
        restart: always
        volumes:
            - apps_persistent:/var/lib/mysql
        ports:
            - 24052:3306
        environment:
            - TZ=Asia/Jakarta
            # - MYSQL_USER=apps_data
            # - MYSQL_PASSWORD=pass_apps_data
            - MYSQL_ROOT_PASSWORD=admin_db
            - MYSQL_DATABASE=apps_docker
volumes:
    apps_persistent: